### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by SeanKilleen**
Supports #338. Putting this here so I can keep things rolling and to give me some public accountability buddies. :)

## Overall Goal
Get a build working successfully for both PRs and master branch builds. 

## Remaining Work

* [x] Basic pipeline setup to get things rolling
* [ ] Add Redis 
* [ ] Add Mysql
* [ ] Add Postgres
* [ ] Add Mongo
* [ ] Configure Environment variables
* [ ] Capture PR number to use in the build scripts
* [ ] Ensure build scripts run
* [ ] Run tests?
* [ ] Create nuget packages
* [ ] Nuget deployment on master build completion

### CODE REVIEW

**Comment by SeanKilleen** [comment]
Lesson Learned: the `@` after the task is the major version of the task. E.g. need to add `PowerShell@2`. I'd had `PowerShell@1` because I'd been confused about what the `@` symbols were doing.

When I was doing it wrong, it was failing with an less-than-intuitive error:

> The term 'D:\a\1\s' is not recognized as the name of a cmdlet, function, script file, or operable program

Also: Really difficult to find out what the latest version of a tool was (I think the understanding is that the UI will do this; references aren't available easily for the YAML). I ended up finding it by looking at the folder names of https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

**Comment by SeanKilleen** [comment]
Note to self: used this repo as a reference: https://github.com/Microsoft/azure-pipelines-tasks

**Comment by mitchdenny** [comment]
If you want a quick reference for the YAML tasks check out this list:

https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=vsts

**Comment by SeanKilleen** [comment]
@mitchdenny yep, had seen that, but thanks for passing along!

**Comment by SeanKilleen** [comment]
Another note from the other thread -- VS2017 includes chocolatey. I'd missed that the machine itself has a repo: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2017-Server2016-Readme.md

**Comment by SeanKilleen** [comment]
Closing this out so I can pick it up again where we are.

**Pull request closed without merging**
